### ISSUE TITLE
Maintainers not added to r-hash team

### ISSUE THREAD

**Issue by nsoranzo** [conda-forge/r-hash-feedstock#2]
The [r-hash team](https://github.com/orgs/conda-forge/teams/r-hash/members) has no members yet, after one week that the repository has been created and 3 days after the maintainers list was updated with the addition of 2 more members in pull request #1.

It seems there's something wrong with the bot that should take care of this. Ping @conda-forge/core

**Comment by jakirkham** [comment]
This is likely caused by issue ( https://github.com/conda-forge/conda-forge.github.io/issues/425 ).

**Comment by jakirkham** [comment]
As a hack, you could resubmit the recipe through `staged-recipes`. Not a great fix for all feedstocks, but it should at least give you permissions here soon.
